// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
//   sqlc-gen-java dev

package com.example.database;

public class City {

    private String slug;
    private String name;

    public City() {}

    public City(final String slug, final String name) {
        this.slug = slug;
        this.name = name;
    }

    public String getSlug() {
        return this.slug;
    }

    public String getName() {
        return this.name;
    }

    public void setSlug(final String slug) {
        this.slug = slug;
    }

    public void setName(final String name) {
        this.name = name;
    }

}
