// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
//   sqlc-gen-java dev

package com.example.database;

public class CreateCityParams {

    private final String name;
    private final String slug;

    CreateCityParams(final String name, final String slug) {
        this.name = name;
        this.slug = slug;
    }

    public String getName() {
        return this.name;
    }

    public String getSlug() {
        return this.slug;
    }

    public static BuilderCreateCityParams builder() {
        return new BuilderCreateCityParams();
    }

    public static class BuilderCreateCityParams {

        private String name;
        private String slug;

        BuilderCreateCityParams() {}

        public BuilderCreateCityParams name(final String name) {
            this.name = name;
            return this;
        }

        public BuilderCreateCityParams slug(final String slug) {
            this.slug = slug;
            return this;
        }

        public CreateCityParams build() {
            return new CreateCityParams(name, slug);
        }
    }
}
