// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
//   sqlc-gen-java dev

package com.example.database;

public class GetVenueParams {

    private final String slug;
    private final String city;

    GetVenueParams(final String slug, final String city) {
        this.slug = slug;
        this.city = city;
    }

    public String getSlug() {
        return this.slug;
    }

    public String getCity() {
        return this.city;
    }

    public static BuilderGetVenueParams builder() {
        return new BuilderGetVenueParams();
    }

    public static class BuilderGetVenueParams {

        private String slug;
        private String city;

        BuilderGetVenueParams() {}

        public BuilderGetVenueParams slug(final String slug) {
            this.slug = slug;
            return this;
        }

        public BuilderGetVenueParams city(final String city) {
            this.city = city;
            return this;
        }

        public GetVenueParams build() {
            return new GetVenueParams(slug, city);
        }
    }
}
