// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
//   sqlc-gen-java dev

package com.example.database;

import java.util.List;

public interface Queries {

    //  Create a new city. The slug must be unique.
    //  This is the second line of the comment
    //  This is the third line
    City createCity(final CreateCityParams params);

    Integer createVenue(final CreateVenueParams params);

    void deleteVenue(final String slug);

    City getCity(final String slug);

    Venue getVenue(final GetVenueParams params);

    List<City> listCities();

    List<Venue> listVenues(final String city);

    void updateCityName(final UpdateCityNameParams params);

    Integer updateVenueName(final UpdateVenueNameParams params);

    List<VenueCountByCityRow> venueCountByCity();
}
