// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
//   sqlc-gen-java dev

package com.example.database;

import java.util.HashMap;
import java.util.Map;

// Venues can be either open or closed
public enum Status {

    OPEN("op!en"),
    CLOSED("clo@sed");

    private static final Map<String, Status> BY_LABEL = new HashMap<>();

    static {
        for (final Status v: values()) {
            BY_LABEL.put(v.label, v);
        }
    }

    public static Status valueOfLabel(final String label) {
        return BY_LABEL.get(label);
    }

    private final String label;

    private Status(final String label) {
        this.label = label;
    }

    public String label() {
        return label;
    }
}
