// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
//   sqlc-gen-java dev

package com.example.database;

public class UpdateVenueNameParams {

    private final String slug;
    private final String name;

    UpdateVenueNameParams(final String slug, final String name) {
        this.slug = slug;
        this.name = name;
    }

    public String getSlug() {
        return this.slug;
    }

    public String getName() {
        return this.name;
    }

    public static BuilderUpdateVenueNameParams builder() {
        return new BuilderUpdateVenueNameParams();
    }

    public static class BuilderUpdateVenueNameParams {

        private String slug;
        private String name;

        BuilderUpdateVenueNameParams() {}

        public BuilderUpdateVenueNameParams slug(final String slug) {
            this.slug = slug;
            return this;
        }

        public BuilderUpdateVenueNameParams name(final String name) {
            this.name = name;
            return this;
        }

        public UpdateVenueNameParams build() {
            return new UpdateVenueNameParams(slug, name);
        }
    }
}
