// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
//   sqlc-gen-java dev

package com.example.database;

public class VenueCountByCityRow {

    private String city;
    private Long count;

    public VenueCountByCityRow() {}

    public VenueCountByCityRow(final String city, final Long count) {
        this.city = city;
        this.count = count;
    }

    public String getCity() {
        return this.city;
    }

    public Long getCount() {
        return this.count;
    }

    public void setCity(final String city) {
        this.city = city;
    }

    public void setCount(final Long count) {
        this.count = count;
    }

}
