// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
//   sqlc-gen-java dev

package com.example.database;

import java.time.LocalDateTime;

// Venues are places where muisc happens
public class Venue {

    private Integer id;
    private Status status;
    private java.util.List<Status> statuses;
    // This value appears in public URLs
    private String slug;
    private String name;
    private String city;
    private String spotifyPlaylist;
    private String songkickId;
    private java.util.List<String> tags;
    private LocalDateTime createdAt;

    public Venue() {}

    public Venue(final Integer id, final Status status, final java.util.List<Status> statuses, final String slug, final String name, final String city, final String spotifyPlaylist, final String songkickId, final java.util.List<String> tags, final LocalDateTime createdAt) {
        this.id = id;
        this.status = status;
        this.statuses = statuses;
        this.slug = slug;
        this.name = name;
        this.city = city;
        this.spotifyPlaylist = spotifyPlaylist;
        this.songkickId = songkickId;
        this.tags = tags;
        this.createdAt = createdAt;
    }

    public Integer getId() {
        return this.id;
    }

    public Status getStatus() {
        return this.status;
    }

    public java.util.Optional<java.util.List<Status>> getStatuses() {
        return java.util.Optional.ofNullable(this.statuses);
    }

    public String getSlug() {
        return this.slug;
    }

    public String getName() {
        return this.name;
    }

    public String getCity() {
        return this.city;
    }

    public String getSpotifyPlaylist() {
        return this.spotifyPlaylist;
    }

    public java.util.Optional<String> getSongkickId() {
        return java.util.Optional.ofNullable(this.songkickId);
    }

    public java.util.Optional<java.util.List<String>> getTags() {
        return java.util.Optional.ofNullable(this.tags);
    }

    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setId(final Integer id) {
        this.id = id;
    }

    public void setStatus(final Status status) {
        this.status = status;
    }

    public void setStatuses(final java.util.List<Status> statuses) {
        this.statuses = statuses;
    }

    public void setSlug(final String slug) {
        this.slug = slug;
    }

    public void setName(final String name) {
        this.name = name;
    }

    public void setCity(final String city) {
        this.city = city;
    }

    public void setSpotifyPlaylist(final String spotifyPlaylist) {
        this.spotifyPlaylist = spotifyPlaylist;
    }

    public void setSongkickId(final String songkickId) {
        this.songkickId = songkickId;
    }

    public void setTags(final java.util.List<String> tags) {
        this.tags = tags;
    }

    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

}
